[project]
name = "trading-app"
version = "0.1.0"
requires-python = ">=3.11"

[dependency-groups]
dev = [
  "numpy==2.4.2",
  "pandas==3.0.0",
  "matplotlib==3.10.8",
  "tqdm==4.67.3",
  "yfinance==1.1.0",
  "black==24.10.0",
]

[tool.black]
line-length = 100
target-version = ["py311"]
